## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
env:
  - DATADEPS_ALWAY_ACCEPT: true
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
notifications:
  email: false
git:
  depth: 99999999
